### ISSUE TITLE
Which license exactly? (GPL-version?)

### ISSUE THREAD

**Issue by dreirund** [tinmarino/dev_one#4]
What is the exact licensing ouf your code?

You write in the `README.md`:

> *License: GPL => Open Source*

Which version of the GPL? Can you clarify? (At best, add a `LICENSE.txt` with the license term to the repository.)

Regards!

**Comment by tinmarino** [comment]
Tk @dreirund, good point it is to proactively license one's work. I am currently investigating the solutions

- Full list
  - https://opensource.org/licenses
- Index for comparing
  - https://choosealicense.com/licenses/
- Option: No License
  - https://choosealicense.com/no-permission/
- Option: WTFPL – Do What the Fuck You Want to Public License
  - https://choosealicense.com/no-permission/

I like people to keep credit of collaborators, (here you, me an @dreirund) but I do not want to enforce it in a license.

**Comment by tinmarino** [comment]
Hi @dreirund, I chose the GPLv2+ as it was already under the GPL version and Linux is under the GPLv2 license.

That was a hard ticket!! I am note really law interested, but then I am covered now. Tk you.

---


This project, DevOne, is licensed under the [GPL v2.0 or later](https://spdx.org/licenses/GPL-2.0-or-later.html)
Copyright &copy; 2020-2022 Martin Tourneboeuf (https://tinmarino.github.io)

**Comment by tinmarino** [comment]
Self-note: see [here](https://softwareengineering.stackexchange.com/a/55328) how to change a license once you picked onces

**Comment by tinmarino** [comment]
@dreirund, do you have a name you'd like to appear in the credits? Or just "Dreirund" lol?

**Comment by dreirund** [comment]
> @dreirund, do you have a name you'd like to appear in the credits? Or just "Dreirund" lol?

I have no desire to be credited at all, but if you _want_ to add credits then add `https://github.com/dreirund`.
