### ISSUE TITLE
[PATCH] [enhancement] Make the build system able to build for different kernel versions.

### ISSUE THREAD

**Issue by dreirund** [tinmarino/dev_one#6]
In the wake of creating an Arch Linux DKMS package out of this, I needed to adapt the `Makefile` to be able to build for specified kernel versions.

This can be achieved by passing the variable `KVER=<kernelversion>` to the `make` command (if not specified, it defaults to `uname -r`).

I suggest that you adopt [&rarr;&hairsp;this change](http://ix.io/4kO7):

```
--- dev_one/Makefile	2023-01-10 13:25:38.079831802 +0100
+++ dev_one.kernelversionsensitive/Makefile	2023-01-10 13:44:37.789796151 +0100
@@ -2,3 +2,4 @@
 
-BUILDSYSTEM_DIR:=/lib/modules/$(shell uname -r)/build
+KVER ?= $(shell uname -r)
+BUILDSYSTEM_DIR ?= /lib/modules/$(KVER)/build
 PWD:=$(shell pwd)
```

Regards!

**Comment by tinmarino** [comment]
Hi @dreirund,

I guess you are still online. Can you please copy in this issue (for reference):

1. Ths error output  (without the change)
2. The good output (without the change)
3. The output of uname -a, and uname -r


Otherwise, I have no objection to merge these changes. Would you mind creating a Pull request? So that the history shows this adition will come from you (i.e. the credit isyours), see more in the license issue #4

**Comment by dreirund** [comment]
Ahoj,

> I guess you are still online. Can you please copy in this issue (for reference):
> 
> 1. Ths error output  (without the change)
> 2. The good output (without the change)

I don't really understand what you mean with "good" and "error" output.

Standard build works fine in both cases, but [DKMS](https://en.wikipedia.org/wiki/Dynamic_Kernel_Module_Support) should be able to build also for other kernels than the currently running kernel, that's why some logic to change the kernel version we want to build for from the default `uname -r` to something that can be overridden.

> 3. The output of uname -a,

`Linux localhost 6.0.0-pf2-longcmdline-custom #2 SMP PREEMPT_DYNAMIC Tue, 18 Oct 2022 10:14:33 +0000 x86_64 GNU/Linux`

> and uname -r

`6.0.0-pf2-longcmdline-custom`

> Would you mind creating a Pull request?

That is too complicated for me. I just provide here my suggestions, and if you do not want to adopt them I will keep them around as patches in the Arch Linux package I create.

> So that the history shows this adition will come from you (i.e. the credit isyours),

I don't want to be credited.

Regards!

**Comment by tinmarino** [comment]
Done in 466ec1b

Hi @dreirund  the good output is the standar otuput of the make command with your change and the bad is the one that failed, the reason why you created the patch in the first place.

I have no problem to integrate your changes by hand, it will help others. I'd just like to understand their meaning for an easier future maintenance.

Anyway, your comment answer my doubt, tk for that.

**Comment by dreirund** [comment]
> Hi @dreirund the good output is the standar otuput of the make command with your change and the bad is the one that failed, the reason why you created the patch in the first place.

Both outputs would be "good" (without any error appearing), but under the hood the module would always be built for the currently running kernel, even if DKMS thinks it would build it for another kernel.

I have not collected any "bad" outputs at all, since I just have implemented it in the first place before trying to use DKMS on it.

Use case is:
* You have more than one kernel installed and want to built the module immediately for all available kernels,
* you upgrade to a new kernel, and the module will be automatically rebuilt directly at kernel upgrade (so it is ready at reboot to the new kernel).

This are things which DKMS can nicely handle if it can pass to the build system the kernel it wants to build the module for.

Thanks for incorporating the changes!

Regards!
